version: '3.4'

services:
  goodfoods.api:
    image: ${DOCKER_REGISTRY-}goodfoodsapi
    build:
      context: .
      dockerfile: GoodFoods.Api/Dockerfile
    ports:
        - 5400:80
        - 5401:443
